<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>comment</key>
    <string>Syntax for log files</string>
    <key>fileTypes</key>
    <array>
        <string>log</string>
    </array>
    <key>name</key>
    <string>Log</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>begin</key>
            <string>^(.*)\s+(TRACE) ?(:|-) (.*) (\[.*\])?</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>log.datetime.text.logs</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>log.keyword.trace.text.logs</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>log.message.trace.text.logs</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>log.message.source.text.logs</string>
                </dict>
            </dict>
            <key>end</key>
            <string>$</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>^(.*)\s+(DEBUG) ?(:|-) (.*) (\[.*\])?</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>log.datetime.text.logs</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>log.keyword.debug.text.logs</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>log.message.debug.text.logs</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>log.message.source.text.logs</string>
                </dict>
            </dict>
            <key>end</key>
            <string>$</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>^(.*)\s+(INFO) ?(:|-) (.*) (\[.*\])?</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>log.datetime.text.logs</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>log.keyword.info.text.logs</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>log.message.info.text.logs</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>log.message.source.text.logs</string>
                </dict>
            </dict>
            <key>end</key>
            <string>$</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>^(.*)\s+(WARN) ?(:|-) (.*) (\[.*\])?</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>log.datetime.text.logs</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>log.keyword.warning.text.logs</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>log.message.warning.text.logs</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>log.message.source.text.logs</string>
                </dict>
            </dict>
            <key>end</key>
            <string>$</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>^(.*)\s+(ERROR) ?(:|-) (.*) (\[.*\])?</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>log.datetime.text.logs</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>log.keyword.error.text.logs</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>log.message.error.text.logs</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>log.message.source.text.logs</string>
                </dict>
            </dict>
            <key>end</key>
            <string>$</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>^(.*)\s+(FATAL) ?(:|-) (.*) (\[.*\])?</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>log.datetime.text.logs</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>log.keyword.fatal.text.logs</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>log.message.fatal.text.logs</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>log.message.source.text.logs</string>
                </dict>
            </dict>
            <key>end</key>
            <string>$</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>^(.*)\s+(STARTED) ?(:|-) (.*) (\[.*\])?</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>log.datetime.text.logs</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>log.keyword.started.text.logs</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>log.message.started.text.logs</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>log.message.source.text.logs</string>
                </dict>
            </dict>
            <key>end</key>
            <string>$</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>^(.*)\s+(FAILED) ?(:|-) (.*) (\[.*\])?</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>log.datetime.text.logs</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>log.keyword.failed.text.logs</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>log.message.failed.text.logs</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>log.message.source.text.logs</string>
                </dict>
            </dict>
            <key>end</key>
            <string>$</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>^(.*)\s+(SUCCEEDED) ?(:|-) (.*) (\[.*\])?</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>log.datetime.text.logs</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>log.keyword.succeeded.text.logs</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>log.message.succeeded.text.logs</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>log.message.source.text.logs</string>
                </dict>
            </dict>
            <key>end</key>
            <string>$</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>^(.*)\s+(SKIPPED) ?(:|-) (.*) (\[.*\])?</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>log.datetime.text.logs</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>log.keyword.skipped.text.logs</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>log.message.skipped.text.logs</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>log.message.source.text.logs</string>
                </dict>
            </dict>
            <key>end</key>
            <string>$</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>^(.*)\s+(SCREENSHOT) ?(:|-) (.*) (\[.*\])?</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>log.datetime.text.logs</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>log.keyword.screenshot.text.logs</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>log.message.screenshot.text.logs</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>log.message.source.text.logs</string>
                </dict>
            </dict>
            <key>end</key>
            <string>$</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\s+at.*</string>
            <key>name</key>
            <string>log.message.error.text.logs</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>text.log</string>
    <key>uuid</key>
    <string>CC24FC5C-C857-4E0A-BDAA-AD1E9ED2E448</string>
</dict>
</plist>
